# Testing automatically if code is running and outputs expected are generated
test:
  stage: test
  image: python:3.10
  before_script:
  - python --version
  script:
    - python -m venv venv
    - venv/Scripts/Activate.ps1 
    - pip install -r stock_model_requirements.txt
    - echo "Successfully installed required packages"
    - python model_european_passenger_car_stock.py
  #artifacts:
  #  reports:
      #junit: src/pytest.xml
  #    codequality: C:/Users/moer_ga/Gitlab-Runner/builds/9ff2XYXUZ/0/fk-tbs/personal-subgroups/gabriel-moring-martinez/eu-stock-model-paper/src/ruff.json


