# Testing automatically if code is running and outputs expected are generated
test:
  image: python:3.10
  stage: test
  script:
    - cd src
    - echo "Working directory: $(pwd)"
    - ls -R  # List all files and folders
    - ./test.sh  # Ensure this generates src/pytest.xml
    - ls -R src  # Verify pytest.xml is in src
  artifacts:
    reports:
      junit: C:/Users/moer_ga/Gitlab-Runner/builds/9ff2XYXUZ/0/fk-tbs/personal-subgroups/gabriel-moring-martinez/eu-stock-model-paper/src/pytest.xml
      codequality: C:/Users/moer_ga/Gitlab-Runner/builds/9ff2XYXUZ/0/fk-tbs/personal-subgroups/gabriel-moring-martinez/eu-stock-model-paper/src/ruff.json


