# Testing automatically if code is running and outputs expected are generated
test:
  image: python:3.10
  stage: test
  script:
    - cd src
    - echo "Current working directory:$(pwd)"
    - ./test.sh


  artifacts:
    reports:
      junit: pytest.xml
      codequality: ruff.json


