# Testing automatically if code is running and outputs expected are generated
test:
  image: python:3.10
  stage: test
  script:
    - cd src
    - echo "Current working directory is: $(pwd)"
    - pwd > current_folder.txt
    - ./test.sh
  artifacts:
    paths:
      - current_folder.txt       # Include the saved path in the artifacts
    reports:
      junit: pytest.xml
      codequality: ruff.json


