# SPDX-FileCopyrightText: 2025 German Aerospace Center
# SPDX-License-Identifier: CC0-1.0
# Testing automatically if code is running and outputs expected are generated
test:
  stage: test
  image: python:3.10
  script:
    - dir
    - ./test.sh

  #artifacts:
  #  reports:
      #junit: src/pytest.xml
  #    codequality: C:/Users/moer_ga/Gitlab-Runner/builds/9ff2XYXUZ/0/fk-tbs/personal-subgroups/gabriel-moring-martinez/eu-stock-model-paper/src/ruff.json


