# Testing automatically if code is running and outputs expected are generated
test:
  image: python:3.10
  stage: test
  script:
    - cd src
    - dir
    - ./test.sh

  artifacts:
    reports:
      junit: src/pytest.xml
      codequality: src/ruff.json


