data:
  input_path: inputs
  output_path: outputs

model:
  start_new_registration_year: 1970
  first_stock_year: 2014
  end_year: 2050
  csp_reference_year: 2021
  csp_available_years: 45
  historical_validation: true
  sensitivity_analysis: true
  historical_csp: true


geography:
  countries:
  use_clusters: true


powertrains:
  - BEV
  - Diesel

survival_rates:
  grouping:
    - geo country
    - powertrain