version = 1

[[annotations]]
path = "outputs/figures/*.pdf"
SPDX-FileCopyrightText = "2025 German Aerospace Center, Gabriel Möring-Martínez"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "outputs/figures/battery_electric_vehicle_stock_shares_eu_27_and_norway_up_to_2050_model_reference_scenario_.png"
SPDX-FileCopyrightText = "2025 German Aerospace Center, Gabriel Möring-Martínez"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "outputs/*.csv"
SPDX-FileCopyrightText = "2025 German Aerospace Center, Gabriel Möring-Martínez"
SPDX-License-Identifier = "CC-BY-4.0"