"""Store fitted discrete survival-rate distribution values."""

# SPDX-FileCopyrightText: 2025 German Aerospace Center, Gabriel Möring-Martínez
# SPDX-License-Identifier: MIT

import pandas as pd

from zevampy.load_data_and_prepare_inputs.dimension_names import survival_rate_dim


def get_distribution_function_discrete_points(survival_rate_distribution_function, survival_rates_country,
                                              predicted_function_value):
    """
    Append predicted survival-rate values to a distribution DataFrame.

    The function replaces the empirical survival-rate values of a country or survival group with predicted values
    from a fitted distribution function and appends the updated data to the output DataFrame.

    Parameters:
        survival_rate_distribution_function (pandas.DataFrame):
            DataFrame containing fitted survival-rate distribution values.

        survival_rates_country (pandas.DataFrame):
            DataFrame containing empirical survival rates for a specific country or survival group.

        predicted_function_value (list or numpy.ndarray):
            Predicted survival-rate values generated by a fitted distribution function.

    Returns:
        pandas.DataFrame:
            Updated DataFrame containing the fitted survival-rate values.
    """
    survival_rates_country = survival_rates_country.reset_index()  # for reseting the index
    survival_rates_country = survival_rates_country.drop(['index'], axis=1)  # deleting the new column of index
    survival_rates_country[survival_rate_dim] = predicted_function_value
    survival_rate_distribution_function = pd.concat([survival_rate_distribution_function, survival_rates_country],
                                                    ignore_index=True)
    return survival_rate_distribution_function
